# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebCrawling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftSoup'
  pod 'Alamofire', '~>5.5'

  # Pods for WebCrawling

end
